name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DOTNET_PROJECT_FOLDER }}
    env:
        DOTNET_PROJECT_FOLDER: ${{ github.workspace }}/src/app
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Restore NuGet dependencies
        run: dotnet restore

      - name: Restore NPM dependencies
        run: npm ci

      - name: Set up UI configuration
        run: sed 's|CI_VARIABLE|BUILD_ONLY|' ./wwwroot/js/src/config.EXAMPLE.js > ./wwwroot/js/src/config.js

      - name: Build UI
        run: ./build-front-end.sh

      - name: Build API
        run: dotnet build
